using System.Net.NetworkInformation;
using PureActive.Network.Abstractions.Extensions;
using PureActive.Network.Abstractions.Networking;
using PureActive.Network.Services.Networking;
using PureActive.Serilog.Sink.Xunit.TestBase;
using Xunit;
using Xunit.Abstractions;

namespace PureActive.Network.Services.IntegrationTests.Network
{
    [Trait("Category", "Integration")]
    public class GatewayIPAddressExtensionsIntegrationTests : TestBaseLoggable<GatewayIPAddressExtensionsIntegrationTests>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GatewayIPAddressExtensionsIntegrationTests"/> class.
        /// </summary>
        /// <param name="testOutputHelper">The test output helper.</param>
        /// <autogeneratedoc />
        public GatewayIPAddressExtensionsIntegrationTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {
            _networkingService  = new NetworkingService(TestLoggerFactory.CreatePureLogger<NetworkingService>());
        }

        private readonly INetworkingService _networkingService;


        [Fact]
        public void GatewayIPAddressExtensions_IPv4OrDefault()
        {
            foreach (var networkInterface in _networkingService.GetAllNetworkInterfaces())
            {
                if (networkInterface.GetIPProperties().GatewayAddresses.IPv4OrDefault() != null)
                {
                    foreach (var unicastIpAddress in networkInterface.GetIPProperties().UnicastAddresses)
                    {
                        TestOutputHelper.WriteLine($"Found IPAddress: {unicastIpAddress.Address}");
                    }
                }
            }
        }
   }
}