// ***********************************************************************
// Assembly         : PureActive.Core.UnitTests
// Author           : SteveBu
// Created          : 11-17-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="FileSystemUnitTests.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.IO;
using FluentAssertions;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging.Abstractions.Internal;
using PureActive.Core.Abstractions.System;
using PureActive.Core.System;
using PureActive.Serilog.Sink.Xunit.TestBase;
using Xunit;
using Xunit.Abstractions;

namespace PureActive.Core.UnitTests.System
{
    /// <summary>
    /// Class FileSystemUnitTests.
    /// Implements the <see cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{FileSystemUnitTests}" />
    /// </summary>
    /// <seealso cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{FileSystemUnitTests}" />
    /// <autogeneratedoc />
    [Trait("Category", "Unit")]
    public class FileSystemUnitTests : TestBaseLoggable<FileSystemUnitTests>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FileSystemUnitTests"/> class.
        /// </summary>
        /// <param name="testOutputHelper">The test output helper.</param>
        /// <autogeneratedoc />
        public FileSystemUnitTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {
        }

        /// <summary>
        /// The application folder name
        /// </summary>
        /// <autogeneratedoc />
        private static readonly string AppFolderName = "FileSystemUnitTests";

        /// <summary>
        /// Files the system configuration root.
        /// </summary>
        /// <param name="appFolderName">Name of the application folder.</param>
        /// <returns>IConfigurationRoot.</returns>
        /// <autogeneratedoc />
        private static IConfigurationRoot FileSystemConfigurationRoot(string appFolderName)
        {
            return new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddEnvironmentVariables()
                .AddInMemoryCollection(
                    new Dictionary<string, string>
                    {
                        ["AppSettings:AppFolderName"] = appFolderName
                    }
                )
                .Build();
        }

        /// <summary>
        /// Defines the test method FileSystem_Constructor_AppFolderName.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void FileSystem_Constructor_AppFolderName()
        {
            var fileSystem = new FileSystem(AppFolderName);

            fileSystem.Should().NotBeNull().And.Subject.As<IFileSystem>().AppFolderName.Should().Be(AppFolderName);
        }


        /// <summary>
        /// Defines the test method FileSystem_Constructor_Configuration.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void FileSystem_Constructor_Configuration()
        {
            var fileSystem = new FileSystem(FileSystemConfigurationRoot(AppFolderName));
            fileSystem.Should().NotBeNull().And.Subject.As<IFileSystem>().AppFolderName.Should().Be(AppFolderName);
        }


        /// <summary>
        /// Defines the test method FileSystem_Constructor_Configuration_Null.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void FileSystem_Constructor_Configuration_Null()
        {
            var fileSystemConfigurationRoot = FileSystemConfigurationRoot(null);

            Func<IFileSystem> act = () => new FileSystem(fileSystemConfigurationRoot);

            act.Should().Throw<ArgumentNullException>().And.ParamName.Should().Be("appFolderName");
        }

        /// <summary>
        /// Defines the test method FileSystem_Constructor_Configuration_OperatingSystem_Null.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void FileSystem_Constructor_Configuration_OperatingSystem_Null()
        {
            var fileSystemConfigurationRoot = FileSystemConfigurationRoot(AppFolderName);

            Func<IFileSystem> act = () => new FileSystem(fileSystemConfigurationRoot, null);
            act.Should().Throw<ArgumentNullException>().And.ParamName.Should().Be("operatingSystem");
        }


        /// <summary>
        /// Defines the test method FileSystem_Constructor_Default.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void FileSystem_Constructor_Default()
        {
            var fileSystem = new FileSystem();
            fileSystem.Should().NotBeNull().And.Subject.As<IFileSystem>().AppFolderName.Should().Be("PureActive/Core");
        }


        /// <summary>
        /// Defines the test method FileSystem_Constructor_Type.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void FileSystem_Constructor_Type()
        {
            var fileSystem = new FileSystem(typeof(FileSystemUnitTests));

            fileSystem.Should().NotBeNull().And.Subject.As<IFileSystem>().AppFolderName.Should()
                .Be(TypeNameHelper.GetTypeDisplayName(typeof(FileSystemUnitTests)).Replace(".", "/"));
        }


        /// <summary>
        /// Defines the test method FileSystem_Constructor_Type_Null.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void FileSystem_Constructor_Type_Null()
        {
            Func<IFileSystem> act = () => new FileSystem((Type) null);

            act.Should().Throw<ArgumentNullException>().And.ParamName.Should().Be("type");
        }

        /// <summary>
        /// Defines the test method FileSystem_Constructor_Type_OperatingSystem_Null.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void FileSystem_Constructor_Type_OperatingSystem_Null()
        {
            // ReSharper disable once ObjectCreationAsStatement
            Func<IFileSystem> act = () => new FileSystem(typeof(FileSystemUnitTests), null);

            act.Should().Throw<ArgumentNullException>().And.ParamName.Should().Be("operatingSystem");
        }
    }
}