// ***********************************************************************
// Assembly         : PureActive.Core.UnitTests
// Author           : SteveBu
// Created          : 11-17-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="TimeProviderUnitTests.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using FluentAssertions;
using PureActive.Core.System;
using PureActive.Serilog.Sink.Xunit.TestBase;
using Xunit;
using Xunit.Abstractions;

namespace PureActive.Core.UnitTests.System
{
    /// <summary>
    /// Class TimeProviderUnitTests.
    /// Implements the <see cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{TimeProviderUnitTests}" />
    /// </summary>
    /// <seealso cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{TimeProviderUnitTests}" />
    /// <autogeneratedoc />
    [Trait("Category", "Unit")]
    public class TimeProviderUnitTests : TestBaseLoggable<TimeProviderUnitTests>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TimeProviderUnitTests"/> class.
        /// </summary>
        /// <param name="testOutputHelper">The test output helper.</param>
        /// <autogeneratedoc />
        public TimeProviderUnitTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {
        }

        /// <summary>
        /// Defines the test method TimeProvider_Constructor.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void TimeProvider_Constructor()
        {
            var timeProvider = new TimeProvider();
            var utcNow = DateTime.UtcNow;
            timeProvider.UtcNow.Should().BeCloseTo(utcNow);
        }
    }
}