// ***********************************************************************
// Assembly         : PureActive.Core.Abstractions
// Author           : SteveBu
// Created          : 10-22-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="IOperatingSystem.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace PureActive.Core.Abstractions.System
{
    /// <summary>
    /// Interface IOperatingSystem
    /// </summary>
    /// <autogeneratedoc />
    public interface IOperatingSystem
    {
        /// <summary>
        /// Determines whether this instance is windows.
        /// </summary>
        /// <returns><c>true</c> if this instance is windows; otherwise, <c>false</c>.</returns>
        /// <autogeneratedoc />
        bool IsWindows();
        /// <summary>
        /// Determines whether this instance is osx.
        /// </summary>
        /// <returns><c>true</c> if this instance is osx; otherwise, <c>false</c>.</returns>
        /// <autogeneratedoc />
        bool IsOsx();
        /// <summary>
        /// Determines whether this instance is linux.
        /// </summary>
        /// <returns><c>true</c> if this instance is linux; otherwise, <c>false</c>.</returns>
        /// <autogeneratedoc />
        bool IsLinux();
    }
}