// ***********************************************************************
// Assembly         : PureActive.Network.Abstractions
// Author           : SteveBu
// Created          : 11-05-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="DhcpOptionType.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace PureActive.Network.Abstractions.DhcpService.Types
{
    /// <summary>
    /// The dhcp defined options.
    /// </summary>
    public enum DhcpOptionType : byte
    {
        /// <summary>
        /// The safe string
        /// </summary>
        /// <autogeneratedoc />
        SafeString,
        /// <summary>
        /// The safe bytes
        /// </summary>
        /// <autogeneratedoc />
        SafeBytes,
        /// <summary>
        /// The message type string
        /// </summary>
        /// <autogeneratedoc />
        MessageTypeString,
        /// <summary>
        /// The physical address skip1 colon string
        /// </summary>
        /// <autogeneratedoc />
        PhysicalAddressSkip1ColonString,
        /// <summary>
        /// The physical address skip1 dash string
        /// </summary>
        /// <autogeneratedoc />
        PhysicalAddressSkip1DashString,
        /// <summary>
        /// The physical address colon string
        /// </summary>
        /// <autogeneratedoc />
        PhysicalAddressColonString,
        /// <summary>
        /// The physical address dash string
        /// </summary>
        /// <autogeneratedoc />
        PhysicalAddressDashString,

        /// <summary>
        /// The ip address
        /// </summary>
        /// <autogeneratedoc />
        IPAddress,
        /// <summary>
        /// The u int16
        /// </summary>
        /// <autogeneratedoc />
        UInt16,
        /// <summary>
        /// The u int32
        /// </summary>
        /// <autogeneratedoc />
        UInt32,
        /// <summary>
        /// The u int16 network
        /// </summary>
        /// <autogeneratedoc />
        UInt16Network,
        /// <summary>
        /// The u int32 network
        /// </summary>
        /// <autogeneratedoc />
        UInt32Network
    }
}