// ***********************************************************************
// Assembly         : PureActive.Network.Abstractions
// Author           : SteveBu
// Created          : 11-05-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="MessageType.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace PureActive.Network.Abstractions.DhcpService.Types
{
    /// <summary>
    /// The message type.
    /// </summary>
    public enum MessageType : byte
    {
        /// <summary>
        /// The unknown
        /// </summary>
        /// <autogeneratedoc />
        Unknown = 0x0,
        /// <summary>
        /// The discover
        /// </summary>
        /// <autogeneratedoc />
        Discover = 0x01,
        /// <summary>
        /// The offer
        /// </summary>
        /// <autogeneratedoc />
        Offer = 0x02,
        /// <summary>
        /// The request
        /// </summary>
        /// <autogeneratedoc />
        Request = 0x03,
        /// <summary>
        /// The decline
        /// </summary>
        /// <autogeneratedoc />
        Decline = 0x04,
        /// <summary>
        /// The ack
        /// </summary>
        /// <autogeneratedoc />
        Ack = 0x05,
        /// <summary>
        /// The nak
        /// </summary>
        /// <autogeneratedoc />
        Nak = 0x06,
        /// <summary>
        /// The release
        /// </summary>
        /// <autogeneratedoc />
        Release = 0x07,
        /// <summary>
        /// The inform
        /// </summary>
        /// <autogeneratedoc />
        Inform = 0x08
    }

    /// <summary>
    /// A class that gets the name of the Message Type.
    /// </summary>
    public static class MessageTypeString
    {
        /// <summary>
        /// Gets the name.
        /// </summary>
        /// <param name="messageTypeEnum">The message type enum.</param>
        /// <returns>System.String.</returns>
        /// <autogeneratedoc />
        public static string GetName(MessageType messageTypeEnum)
        {
            switch (messageTypeEnum)
            {
                case MessageType.Discover:
                    return "Discover";
                case MessageType.Offer:
                    return "Offer";
                case MessageType.Request:
                    return "Request";
                case MessageType.Decline:
                    return "Decline";
                case MessageType.Ack:
                    return "Ack";
                case MessageType.Nak:
                    return "Nak";
                case MessageType.Release:
                    return "Release";
                case MessageType.Inform:
                    return "Inform";
                default:
                    return "Unknown";
            }
        }
    }
}