// ***********************************************************************
// Assembly         : PureActive.Network.Abstractions
// Author           : SteveBu
// Created          : 11-05-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="OperationCode.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace PureActive.Network.Abstractions.DhcpService.Types
{
    /// <summary>
    /// The operation code (OP) type.
    /// </summary>
    public enum OperationCode : byte
    {
        /// <summary>
        /// The boot request
        /// </summary>
        /// <autogeneratedoc />
        BootRequest = 0x01,
        /// <summary>
        /// The boot reply
        /// </summary>
        /// <autogeneratedoc />
        BootReply = 0x02
    }

    /// <summary>
    /// A class that gets the name of the Operations Code (OP).
    /// </summary>
    public static class OperationString
    {
        /// <summary>
        /// Gets the name.
        /// </summary>
        /// <param name="operationEnum">The operation enum.</param>
        /// <returns>System.String.</returns>
        /// <autogeneratedoc />
        public static string GetName(OperationCode operationEnum)
        {
            switch (operationEnum)
            {
                case OperationCode.BootRequest:
                    return "BootRequest";
                case OperationCode.BootReply:
                    return "BootReply";
                default:
                    return "Unknown";
            }
        }
    }
}