// ***********************************************************************
// Assembly         : PureActive.Queue.Hangfire.IntegrationTests
// Author           : SteveBu
// Created          : 11-17-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="QueueHangfireIntegrationTests.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************

using System;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Autofac;
using FluentAssertions;
using Hangfire;
using Hangfire.SQLite;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using PureActive.Core.Abstractions.Queue;
using PureActive.Core.Abstractions.System;
using PureActive.Core.Extensions;
using PureActive.Hosting.Abstractions.Types;
using PureActive.Hosting.Configuration;
using PureActive.Hosting.Settings;
using PureActive.Logging.Abstractions.Interfaces;
using PureActive.Queue.Hangfire.Queue;
using PureActive.Serilog.Sink.Xunit.TestBase;
using Serilog.Events;
using Xunit;
using Xunit.Abstractions;

namespace PureActive.Queue.Hangfire.IntegrationTests
{
    /// <summary>
    /// Class QueueHangfireIntegrationTests.
    /// Implements the <see cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{QueueHangfireIntegrationTests}" />
    /// </summary>
    /// <seealso cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{QueueHangfireIntegrationTests}" />
    /// <autogeneratedoc />
    [Trait("Category", "Integration")]
    public class QueueHangfireIntegrationTests : TestBaseLoggable<QueueHangfireIntegrationTests>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueueHangfireIntegrationTests"/> class.
        /// </summary>
        /// <param name="testOutputHelper">The test output helper.</param>
        /// <autogeneratedoc />
        public QueueHangfireIntegrationTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {
        }


        [ExcludeFromCodeCoverage]
        private class StartupHangfireTest : StartupSettings
        {
            /// <inheritdoc />
            public StartupHangfireTest(IConfiguration configuration, IHostingEnvironment hostingEnvironment,
                IPureLoggerFactory loggerFactory, IFileSystem fileSystem, IOperatingSystem operatingSystem) :
                base(configuration, hostingEnvironment, loggerFactory, ServiceHost.HangfireTest, fileSystem,
                    operatingSystem)
            {

            }

            /// <inheritdoc />
            public override void ApplyDatabaseMigrations(IApplicationBuilder app)
            {

            }

            // This method gets called by the runtime. Use this method to add services to the container.
            public IServiceProvider ConfigureServices(IServiceCollection services)
            {
                if (services == null) throw new ArgumentNullException(nameof(services));

                var builder = RegisterSharedServices(services);

                // Register JobQueue client
                builder.RegisterJobQueueClient();
                builder.RegisterType<HangFireTestService>().As<IHangFireTestService>();

                services.AddHangfireQueue(GetConnectionString(ServiceHost.Hangfire), LoggerFactory);

                return BuildContainer(builder, services);
            }

            public void Configure(IApplicationBuilder app, IHostingEnvironment env)
            {
                if (app == null) throw new ArgumentNullException(nameof(app));
                if (env == null) throw new ArgumentNullException(nameof(env));

                app.UseHangfireQueueDashboard(Container);
            }

        }

        private static readonly string LogFileName = "hangfire-test.log";

        private static IWebHost BuildWebHost<TStartup>(string[] args) where TStartup : class
        {
            var webHostBuilder = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    var env = hostingContext.HostingEnvironment;

                    config.AddAppSettings(env);
                    config.AddEnvironmentVariables();
                    config.AddCommandLine(args);
                });


            webHostBuilder
                .UseSystemSettings(LogFileName, IncludeLogEvent)
                .UseApplicationInsights()
                .UseStartup<TStartup>();


            return webHostBuilder.Build();
        }

        [ExcludeFromCodeCoverage]
        private static bool IncludeLogEvent(LogEvent logEvent)
        {
            return true;
        }

        /// <summary>
        /// Defines the test method Runs Hangfire Service
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public async Task QueueHangfire_Run()
        {
            var webHost = BuildWebHost<StartupHangfireTest>(new string[0]);
            webHost.Should().NotBeNull().And.Subject.Should().BeAssignableTo<IWebHost>();

            var cts = new CancellationTokenSource();

            cts.CancelAfter(500);
            await webHost.RunAsync(cts.Token);
        }

        [ExcludeFromCodeCoverage]

        public class HangfireJob
        {
            public string TestValue { get; }

            public HangfireJob(string testValue)
            {
                TestValue = testValue;
            }
        }

        private interface IHangFireTestService
        {
            Task ExecuteHangfireTestJobAsync(HangfireJob hangfireJob);
        }

        [ExcludeFromCodeCoverage]

        public class HangFireTestService : IHangFireTestService
        {
            /// <inheritdoc />
            public Task ExecuteHangfireTestJobAsync(HangfireJob hangfireJob)
            {
                return Task.Run( () => Console.WriteLine($"Job TestValue: {hangfireJob.TestValue}")
                    );
            }
        }

        /// <summary>
        /// Defines the test method Runs Hangfire Service
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public async Task QueueHangfire_JobQueue()
        {
            var webHost = BuildWebHost<StartupHangfireTest>(new string[0]);
            webHost.Should().NotBeNull().And.Subject.Should().BeAssignableTo<IWebHost>();
        
            var jobQueueClient = webHost.Services.GetService(typeof(IJobQueueClient)).As<IJobQueueClient>();
            jobQueueClient.Should().NotBeNull().And.Subject.Should().BeAssignableTo<IJobQueueClient>();

            const string testValue = "TestValue";

            var hangFireJob = new HangfireJob(testValue);
            var jobId = await jobQueueClient.EnqueueAsync<IHangFireTestService>(
                service => service.ExecuteHangfireTestJobAsync(hangFireJob));

            var jobState = await jobQueueClient.GetJobStatusAsync(jobId);
            jobState.Should().NotBeNull();

            var cts = new CancellationTokenSource();

            cts.CancelAfter(5000);
            await webHost.RunAsync(cts.Token);

            jobState = await jobQueueClient.GetJobStatusAsync(jobId);
            jobState.Should().NotBeNull();
        }

        private string GetConnectionString(ServiceHost serviceHost)
        {
            var databasePath = FileSystem.DataFolderPath() + serviceHost + ".db";

            return $"Data Source={databasePath};";
        }

        /// <summary>
        /// Defines the test method Runs JobQueue
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public async Task QueueHangfire_Standalone_JobQueue()
        {
            GlobalConfiguration.Configuration.UseSQLiteStorage(GetConnectionString(ServiceHost.HangfireTest));

            using (var server = new BackgroundJobServer())
            {
                server.Should().NotBeNull();

                var jobIdString = BackgroundJob.Enqueue(() => Console.WriteLine($"Enqueued Task{Guid.NewGuid().ToStringNoDashes()}"));
                jobIdString.Should().NotBeNull();
                int.TryParse(jobIdString, out var jobId).Should().BeTrue();

                await Task.Delay(10000);
            }
        }


    }
}