// ***********************************************************************
// Assembly         : PureActive.Network.Abstractions
// Author           : SteveBu
// Created          : 11-02-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="DevicePlatform.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace PureActive.Network.Abstractions.Types
{
    // ReSharper disable InconsistentNaming

    /// <summary>
    /// Enum DevicePlatform
    /// </summary>
    /// <autogeneratedoc />
    public enum DevicePlatform
    {
        /// <summary>
        /// The unknown
        /// </summary>
        /// <autogeneratedoc />
        Unknown = 0,
        /// <summary>
        /// The android
        /// </summary>
        /// <autogeneratedoc />
        Android,
        /// <summary>
        /// The i os
        /// </summary>
        /// <autogeneratedoc />
        iOS,
        /// <summary>
        /// The windows phone
        /// </summary>
        /// <autogeneratedoc />
        WindowsPhone,
        /// <summary>
        /// The windows
        /// </summary>
        /// <autogeneratedoc />
        Windows,
        /// <summary>
        /// The windows tablet
        /// </summary>
        /// <autogeneratedoc />
        WindowsTablet,
        /// <summary>
        /// The surface hub
        /// </summary>
        /// <autogeneratedoc />
        SurfaceHub,
        /// <summary>
        /// The xbox
        /// </summary>
        /// <autogeneratedoc />
        Xbox,
        /// <summary>
        /// The io t
        /// </summary>
        /// <autogeneratedoc />
        IoT,
        /// <summary>
        /// The tv os
        /// </summary>
        /// <autogeneratedoc />
        tvOS,
        /// <summary>
        /// The watch os
        /// </summary>
        /// <autogeneratedoc />
        watchOS,
        /// <summary>
        /// The mac os
        /// </summary>
        /// <autogeneratedoc />
        macOS,
        /// <summary>
        /// The tizen
        /// </summary>
        /// <autogeneratedoc />
        Tizen
    }

    // ReSharper restore InconsistentNaming
}