// ***********************************************************************
// Assembly         : PureActive.Core.IntegrationTests
// Author           : SteveBu
// Created          : 11-17-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-29-2018
// ***********************************************************************
// <copyright file="NetworkingServiceIntegrationTests.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************

using FluentAssertions;
using PureActive.Network.Abstractions.Networking;
using PureActive.Network.Services.Networking;
using PureActive.Serilog.Sink.Xunit.TestBase;
using Xunit;
using Xunit.Abstractions;

namespace PureActive.Network.IntegrationTests.Networking
{
    /// <summary>
    /// Class NetworkingServiceIntegrationTests.
    /// Implements the <see cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{NetworkingServiceIntegrationTests}" />
    /// </summary>
    /// <seealso cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{NetworkingServiceIntegrationTests}" />
    /// <autogeneratedoc />
    [Trait("Category", "Integration")]
    public class NetworkingServiceIntegrationTests : TestBaseLoggable<NetworkingServiceIntegrationTests>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkingServiceIntegrationTests"/> class.
        /// </summary>
        /// <param name="testOutputHelper">The test output helper.</param>
        /// <autogeneratedoc />
        public NetworkingServiceIntegrationTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {
            _networkingService = new NetworkingService(TestLoggerFactory.CreatePureLogger<NetworkingService>());
        }

        /// <summary>
        /// The file system
        /// </summary>
        /// <autogeneratedoc />
        private readonly INetworkingService _networkingService;

        [Fact]
        public void NetworkingService_Constructor()
        {
            _networkingService.Should().NotBeNull().And.Subject.Should().BeAssignableTo<INetworkingService>();
        }
    }
}