// ***********************************************************************
// Assembly         : PureActive.Core
// Author           : SteveBu
// Created          : 11-01-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="OperationRunner.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using PureActive.Core.Abstractions.Async;
using PureActive.Logging.Abstractions.Interfaces;

namespace PureActive.Core.Async
{
    /// <summary>
    /// Functionality to execute one or more generic operations
    /// with fallback behavior.
    /// Implements the <see cref="PureActive.Core.Abstractions.Async.IOperationRunner" />
    /// </summary>
    /// <seealso cref="PureActive.Core.Abstractions.Async.IOperationRunner" />
    public class OperationRunner : IOperationRunner
    {
        /// <summary>
        /// The logger.
        /// </summary>
        private readonly IPureLogger<OperationRunner> _logger;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="logger">The logger.</param>
        public OperationRunner(IPureLogger<OperationRunner> logger)
        {
            _logger = logger;
        }

        /// <summary>
        /// Executes a set of operations in parallel, with a limit
        /// on the maximum number of simultaneous operations.
        /// </summary>
        /// <typeparam name="TSource">The type of the t source.</typeparam>
        /// <typeparam name="TResult">The type of the t result.</typeparam>
        /// <param name="sources">The sources.</param>
        /// <param name="operation">The operation.</param>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <param name="maxSimultaneous">The maximum simultaneous.</param>
        /// <returns>Task&lt;IList&lt;TResult&gt;&gt;.</returns>
        /// <autogeneratedoc />
        public async Task<IList<TResult>> RunOperationsAsync<TSource, TResult>(
            IEnumerable<TSource> sources,
            Func<TSource, Task<TResult>> operation,
            CancellationToken cancellationToken,
            int maxSimultaneous
        )
        {
            // Enumerate once to List and use twice below
            var sourcesList = sources.ToList();

            var currentlyRunningTasks = sourcesList
                .Select(operation)
                .Take(maxSimultaneous)
                .ToList();

            var sourcesWaitingToStart = sourcesList
                .Skip(maxSimultaneous)
                .ToList();

            var results = new List<TResult>();

            while (sourcesWaitingToStart.Any() && !cancellationToken.IsCancellationRequested)
            {
                var completedTask = await Task.WhenAny(currentlyRunningTasks);
                results.Add(completedTask.Result);
                currentlyRunningTasks.Remove(completedTask);

                var nextSource = sourcesWaitingToStart.First();
                sourcesWaitingToStart.Remove(nextSource);
                currentlyRunningTasks.Add(operation(nextSource));
            }

            var remainingResults = await Task.WhenAll(currentlyRunningTasks);
            results.AddRange(remainingResults);

            return results;
        }


        /// <summary>
        /// Executes an operation, retrying the operation if needed.
        /// </summary>
        /// <param name="operation">The operation.</param>
        /// <param name="shouldRetry">The should retry.</param>
        /// <param name="numAttempts">The number attempts.</param>
        /// <param name="delayBetweenRetries">The delay between retries.</param>
        /// <param name="defaultResultIfFailed">if set to <c>true</c> [default result if failed].</param>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <returns>Task.</returns>
        /// <autogeneratedoc />
        public Task RetryOperationIfNeededAsync(
            Func<Task> operation,
            Func<Exception, bool> shouldRetry,
            int numAttempts,
            TimeSpan delayBetweenRetries,
            bool defaultResultIfFailed,
            CancellationToken cancellationToken)
        {
            return RetryOperationIfNeededAsync
            (
                async () =>
                {
                    await operation();
                    return true;
                },
                shouldRetry,
                numAttempts,
                delayBetweenRetries,
                defaultResultIfFailed,
                cancellationToken
            );
        }

        /// <summary>
        /// Executes an operation, retrying the operation if needed.
        /// </summary>
        /// <typeparam name="TResult">The type of the t result.</typeparam>
        /// <param name="operation">The operation.</param>
        /// <param name="shouldRetry">The should retry.</param>
        /// <param name="numAttempts">The number attempts.</param>
        /// <param name="delayBetweenRetries">The delay between retries.</param>
        /// <param name="defaultResultIfFailed">if set to <c>true</c> [default result if failed].</param>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <returns>Task&lt;TResult&gt;.</returns>
        /// <exception cref="InvalidOperationException">Not reachable.</exception>
        /// <autogeneratedoc />
        public async Task<TResult> RetryOperationIfNeededAsync<TResult>(
            Func<Task<TResult>> operation,
            Func<Exception, bool> shouldRetry,
            int numAttempts,
            TimeSpan delayBetweenRetries,
            bool defaultResultIfFailed,
            CancellationToken cancellationToken)
        {
            for (var attempt = 1; attempt <= numAttempts; attempt++)
                try
                {
                    return await operation();
                }
                catch (Exception ex)
                {
                    var tryAgain = attempt < numAttempts && shouldRetry(ex) &&
                                   !cancellationToken.IsCancellationRequested;

                    _logger?.LogWarning
                    (
                        0,
                        ex,
                        tryAgain
                            ? "Failed operation on attempt {attempt}. Retrying."
                            : "Permanently failed on attempt {attempt}.",
                        attempt
                    );

                    if (!tryAgain)
                        if (defaultResultIfFailed)
                            return default(TResult);
                        else
                            throw;
                }

            throw new InvalidOperationException("Not reachable.");
        }

        /// <summary>
        /// Runs a given operation with a timeout. Returns whether the
        /// operation completed within the given amount of time.
        /// </summary>
        /// <param name="operation">The operation.</param>
        /// <param name="timeout">The timeout.</param>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <returns>Task&lt;System.Boolean&gt;.</returns>
        /// <autogeneratedoc />
        public async Task<bool> RunOperationWithTimeoutAsync(
            Func<Task> operation,
            TimeSpan timeout,
            CancellationToken cancellationToken)
        {
            var operationTask = operation();
            var timeoutTask = Task.Delay(timeout, cancellationToken);

            var taskFinishedFirst = await Task.WhenAny(operationTask, timeoutTask);

            return taskFinishedFirst == operationTask;
        }
    }
}