// ***********************************************************************
// Assembly         : PureActive.Network.Extensions
// Author           : SteveBu
// Created          : 11-02-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="ByteOrder.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace PureActive.Network.Extensions.IO
{
    /// <summary>
    /// Enum ByteOrder
    /// </summary>
    /// <autogeneratedoc />
    public enum ByteOrder
    {
        /// <summary>
        /// Use the default byte order for the computer.
        /// </summary>
        Default = 0,

        /// <summary>
        /// Use big-endian byte order, also known as Motorola byte order.
        /// </summary>
        BigEndian = 1,

        /// <summary>
        /// Use little-endian byte order, also known as Intel byte order.
        /// </summary>
        LittleEndian = 2,

        /// <summary>
        /// Use Motorola byte order. Corresponds to <see cref="BigEndian" />.
        /// </summary>
        Motorola = BigEndian,

        /// <summary>
        /// Use Intel byte order. Corresponds to <see cref="LittleEndian" />.
        /// </summary>
        Intel = LittleEndian,

        /// <summary>
        /// The order which multi-byte values are transmitted on a network.
        /// </summary>
        Network = BigEndian
    }
}