// ***********************************************************************
// Assembly         : PureActive.Network.Abstractions
// Author           : SteveBu
// Created          : 11-02-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="ArpItem.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Net;
using System.Net.NetworkInformation;

namespace PureActive.Network.Abstractions.ArpService
{
    /// <summary>
    /// Class ArpItem.
    /// </summary>
    /// <autogeneratedoc />
    public class ArpItem
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ArpItem"/> class.
        /// </summary>
        /// <param name="physicalAddress">The physical address.</param>
        /// <param name="ipAddress">The ip address.</param>
        /// <param name="createdTimestamp">The created timestamp.</param>
        /// <autogeneratedoc />
        public ArpItem(PhysicalAddress physicalAddress, IPAddress ipAddress, DateTimeOffset createdTimestamp)
        {
            PhysicalAddress = physicalAddress;
            IPAddress = ipAddress;
            CreatedTimestamp = createdTimestamp;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ArpItem"/> class.
        /// </summary>
        /// <param name="physicalAddress">The physical address.</param>
        /// <param name="ipAddress">The ip address.</param>
        /// <autogeneratedoc />
        public ArpItem(PhysicalAddress physicalAddress, IPAddress ipAddress) : this(physicalAddress, ipAddress,
            DateTimeOffset.Now)
        {
        }

        /// <summary>
        /// Gets or sets the physical address.
        /// </summary>
        /// <value>The physical address.</value>
        /// <autogeneratedoc />
        public PhysicalAddress PhysicalAddress { get; set; }
        /// <summary>
        /// Gets or sets the ip address.
        /// </summary>
        /// <value>The ip address.</value>
        /// <autogeneratedoc />
        public IPAddress IPAddress { get; set; }
        /// <summary>
        /// Gets or sets the created timestamp.
        /// </summary>
        /// <value>The created timestamp.</value>
        /// <autogeneratedoc />
        public DateTimeOffset CreatedTimestamp { get; set; }
    }
}