// ***********************************************************************
// Assembly         : PureActive.Network.Abstractions
// Author           : SteveBu
// Created          : 11-05-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-05-2018
// ***********************************************************************
// <copyright file="INetworkMapService.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using PureActive.Hosting.Abstractions.System;
using PureActive.Network.Abstractions.CommonNetworkServices;
using PureActive.Network.Abstractions.Network;

namespace PureActive.Network.Abstractions.NetworkMapService
{
    /// <summary>
    /// Interface INetworkMapService
    /// Implements the <see cref="IHostedServiceInternal" />
    /// </summary>
    /// <seealso cref="IHostedServiceInternal" />
    /// <autogeneratedoc />
    public interface INetworkMapService : IHostedServiceInternal
    {
        /// <summary>
        /// Gets the common services.
        /// </summary>
        /// <value>The common services.</value>
        /// <autogeneratedoc />
        ICommonServices CommonServices { get; }

        /// <summary>
        /// Gets the common network services.
        /// </summary>
        /// <value>The common network services.</value>
        /// <autogeneratedoc />
        ICommonNetworkServices CommonNetworkServices { get; }

        /// <summary>
        /// Gets the network map.
        /// </summary>
        /// <value>The network map.</value>
        /// <autogeneratedoc />
        INetworkMap NetworkMap { get; }
    }
}