// ***********************************************************************
// Assembly         : PureActive.Hosting.Abstractions
// Author           : SteveBu
// Created          : 11-01-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="IHostedServiceInternal.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using Microsoft.Extensions.Hosting;
using PureActive.Hosting.Abstractions.Types;
using PureActive.Logging.Abstractions.Interfaces;

namespace PureActive.Hosting.Abstractions.System
{
    /// <summary>
    /// Interface IHostedServiceInternal
    /// Implements the <see cref="IHostedService" />
    /// Implements the <see cref="IPureLoggable" />
    /// </summary>
    /// <seealso cref="IHostedService" />
    /// <seealso cref="IPureLoggable" />
    /// <autogeneratedoc />
    public interface IHostedServiceInternal : IHostedService, IPureLoggable
    {
        /// <summary>
        /// Gets the service host status.
        /// </summary>
        /// <value>The service host status.</value>
        /// <autogeneratedoc />
        ServiceHostStatus ServiceHostStatus { get; }
    }
}