// ***********************************************************************
// Assembly         : PureActive.Logger.Provider.Serilog
// Author           : SteveBu
// Created          : 11-05-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="PureSeriLogContext.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using PureActive.Logging.Abstractions.Interfaces;
using Serilog.Context;
using Serilog.Core;
using Serilog.Core.Enrichers;

namespace PureActive.Logger.Provider.Serilog.Types
{
    /// <summary>
    /// Allows for adding additional properties to all log messages
    /// logged within newly created scopes.
    /// Implements the <see cref="IPureLogContext" />
    /// </summary>
    /// <seealso cref="IPureLogContext" />
    public class PureSeriLogContext : IPureLogContext
    {
        /// <summary>
        /// Creates a new log scope, with the given properties.
        /// </summary>
        /// <param name="properties">The properties.</param>
        /// <returns>IDisposable.</returns>
        /// <autogeneratedoc />
        public IDisposable CreateLogScope(IList<KeyValuePair<string, string>> properties)
        {
            return LogContext.Push
            (
                properties.Select
                    (
                        p => new PropertyEnricher(p.Key, p.Value)
                    ).Cast<ILogEventEnricher>()
                    .ToArray()
            );
        }
    }
}