// ***********************************************************************
// Assembly         : PureActive.Logger.Provider.Serilog.UnitTests
// Author           : SteveBu
// Created          : 11-26-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-26-2018
// ***********************************************************************
// <copyright file="PureSeriLoggerConfigurationTests.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using FluentAssertions;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using PureActive.Core.System;
using PureActive.Logger.Provider.Serilog.Configuration;
using PureActive.Serilog.Sink.Xunit.TestBase;
using Xunit;
using Xunit.Abstractions;

namespace PureActive.Logger.Provider.Serilog.UnitTests.Configuration
{
    /// <summary>
    /// Class PureSeriLoggerConfigurationTests.
    /// Implements the <see cref="PureActive.Serilog.Sink.Xunit.TestBase.TestBaseLoggable{PureActive.Logger.Provider.Serilog.UnitTests.Configuration.PureSeriLoggerConfigurationTests}" />
    /// </summary>
    /// <seealso cref="PureActive.Serilog.Sink.Xunit.TestBase.TestBaseLoggable{PureActive.Logger.Provider.Serilog.UnitTests.Configuration.PureSeriLoggerConfigurationTests}" />
    /// <autogeneratedoc />
    [Trait("Category", "Unit")]
    public class PureSeriLoggerConfigurationTests : TestBaseLoggable<PureSeriLoggerConfigurationTests>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PureSeriLoggerConfigurationTests"/> class.
        /// </summary>
        /// <param name="testOutputHelper">The test output helper.</param>
        /// <autogeneratedoc />
        public PureSeriLoggerConfigurationTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {

        }

        /// <summary>
        /// Defines the test method PureSeriLoggerConfiguration_AddLoggerSettings.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void PureSeriLoggerConfiguration_AddLoggerSettings()
        {
            var fileSystem = new FileSystem();

            var configuration = new ConfigurationBuilder()
                .SetBasePath(fileSystem.GetCurrentDirectory())
                .AddLoggerSettings(LogLevel.Debug)
                .AddEnvironmentVariables()
                .Build();

            configuration.Should().NotBeNull();
        }

    }
}