// ***********************************************************************
// Assembly         : PureActive.Hosting
// Author           : SteveBu
// Created          : 11-03-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-03-2018
// ***********************************************************************
// <copyright file="OperationIdProvider.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using Microsoft.ApplicationInsights.DataContracts;
using Microsoft.AspNetCore.Http;
using PureActive.Logging.Abstractions.Interfaces;

namespace PureActive.Hosting.Logging
{
    /// <summary>
    /// Provides the operation ID of the current request.
    /// Implements the <see cref="IOperationIdProvider" />
    /// </summary>
    /// <seealso cref="IOperationIdProvider" />
    public class OperationIdProvider : IOperationIdProvider
    {
        /// <summary>
        /// The HTTP context accessor.
        /// </summary>
        private readonly IHttpContextAccessor _httpContextAccessor;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="httpContextAccessor">The HTTP context accessor.</param>
        public OperationIdProvider(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        /// <summary>
        /// The operation ID of the current request.
        /// </summary>
        /// <value>The operation identifier.</value>
        /// <autogeneratedoc />
        public string OperationId => _httpContextAccessor
            .HttpContext
            .Features
            .Get<RequestTelemetry>()
            .Id;
    }
}