// ***********************************************************************
// Assembly         : PureActive.Network.Abstractions
// Author           : SteveBu
// Created          : 11-02-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="PingReplyEventArgs.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Net.NetworkInformation;
using System.Threading;

namespace PureActive.Network.Abstractions.PingService.Events
{
    /// <summary>
    /// Class PingReplyEventArgs.
    /// Implements the <see cref="System.EventArgs" />
    /// </summary>
    /// <seealso cref="System.EventArgs" />
    /// <autogeneratedoc />
    public class PingReplyEventArgs : EventArgs
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PingReplyEventArgs"/> class.
        /// </summary>
        /// <param name="pingJob">The ping job.</param>
        /// <param name="pingReply">The ping reply.</param>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <exception cref="ArgumentNullException">pingReply</exception>
        /// <autogeneratedoc />
        public PingReplyEventArgs(PingJob pingJob, PingReply pingReply, CancellationToken cancellationToken)
        {
            PingJob = pingJob;
            PingReply = pingReply ?? throw new ArgumentNullException(nameof(pingReply));
            CancellationToken = cancellationToken;
        }

        /// <summary>
        /// Gets the ping job.
        /// </summary>
        /// <value>The ping job.</value>
        /// <autogeneratedoc />
        public PingJob PingJob { get; }
        /// <summary>
        /// Gets the ping reply.
        /// </summary>
        /// <value>The ping reply.</value>
        /// <autogeneratedoc />
        public PingReply PingReply { get; }
        /// <summary>
        /// Gets the cancellation token.
        /// </summary>
        /// <value>The cancellation token.</value>
        /// <autogeneratedoc />
        public CancellationToken CancellationToken { get; }
    }
}