// ***********************************************************************
// Assembly         : PureActive.Network.Abstractions
// Author           : SteveBu
// Created          : 11-02-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="PingReplyEventHandler.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace PureActive.Network.Abstractions.PingService.Events
{
    /// <summary>
    /// Delegate PingReplyEventHandler
    /// </summary>
    /// <param name="sender">The sender.</param>
    /// <param name="args">The <see cref="PingReplyEventArgs"/> instance containing the event data.</param>
    /// <autogeneratedoc />
    public delegate void PingReplyEventHandler(object sender, PingReplyEventArgs args);
}