// ***********************************************************************
// Assembly         : PureActive.Network.Devices.UnitTests
// Author           : SteveBu
// Created          : 11-17-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="NetworkDevicesUnitTests.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using PureActive.Serilog.Sink.Xunit.TestBase;
using Xunit;
using Xunit.Abstractions;

namespace PureActive.Network.Devices.UnitTests
{
    /// <summary>
    /// Class NetworkDevicesUnitTests.
    /// Implements the <see cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{NetworkDevicesUnitTests}" />
    /// </summary>
    /// <seealso cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{NetworkDevicesUnitTests}" />
    /// <autogeneratedoc />
    [Trait("Category", "Unit")]
    public class NetworkDevicesUnitTests : TestBaseLoggable<NetworkDevicesUnitTests>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkDevicesUnitTests" /> class.
        /// </summary>
        /// <param name="testOutputHelper">The test output helper.</param>
        /// <autogeneratedoc />
        public NetworkDevicesUnitTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {
        }

        /// <summary>
        /// Defines the test method NetworkDevices_Create.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void NetworkDevices_Create()
        {
        }
    }
}