// ***********************************************************************
// Assembly         : PureActive.Network.Abstractions
// Author           : SteveBu
// Created          : 11-02-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="IComputer.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using PureActive.Network.Abstractions.NetworkDevice;

namespace PureActive.Network.Abstractions.Computer
{
    /// <summary>
    /// Interface IComputer
    /// Implements the <see cref="INetworkDevice" />
    /// </summary>
    /// <seealso cref="INetworkDevice" />
    /// <autogeneratedoc />
    public interface IComputer : INetworkDevice
    {
    }
}