// ***********************************************************************
// Assembly         : PureActive.Serilog.Sink.Xunit
// Author           : SteveBu
// Created          : 11-01-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="IPureLoggerFactory.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using PureActive.Logging.Abstractions.Interfaces;

namespace PureActive.Serilog.Sink.Xunit.Interfaces
{
    /// <summary>
    /// Interface IPureTestLoggerFactory
    /// Implements the <see cref="IPureLoggerFactory" />
    /// </summary>
    /// <seealso cref="IPureLoggerFactory" />
    /// <autogeneratedoc />
    public interface IPureTestLoggerFactory : IPureLoggerFactory
    {
    }
}