// ***********************************************************************
// Assembly         : PureActive.Core.UnitTests
// Author           : SteveBu
// Created          : 11-17-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-29-2018
// ***********************************************************************
// <copyright file="NetworkingServiceUnitTests.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************


using System;
using System.Net;
using FluentAssertions;
using PureActive.Hosting.Abstractions.Extensions;
using PureActive.Hosting.Abstractions.Networking;
using PureActive.Hosting.Networking;
using PureActive.Serilog.Sink.Xunit.TestBase;
using Xunit;
using Xunit.Abstractions;

namespace PureActive.Hosting.UnitTests.Networking
{
    /// <summary>
    /// Class NetworkingServiceUnitTests.
    /// Implements the <see cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{NetworkingServiceUnitTests}" />
    /// </summary>
    /// <seealso cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{NetworkingServiceUnitTests}" />
    /// <autogeneratedoc />
    [Trait("Category", "Unit")]
    public class NetworkingServiceUnitTests : TestBaseLoggable<NetworkingServiceUnitTests>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkingServiceUnitTests"/> class.
        /// </summary>
        /// <param name="testOutputHelper">The test output helper.</param>
        /// <autogeneratedoc />
        public NetworkingServiceUnitTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {
            _networkingService = new NetworkingService(TestLoggerFactory.CreatePureLogger<NetworkingService>());
        }

        private readonly INetworkingService _networkingService;

        [Fact]
        public void NetworkingService_Constructor()
        {
            _networkingService.Should().NotBeNull().And.Subject.Should().BeAssignableTo<INetworkingService>();
        }
        

        [Fact]
        public void NetworkingService_GetNetworkAddress_InvalidSubnet()
        {
            IPAddress ipAddressV6 = IPAddress.IPv6None;

            Func<IPAddress> fx = () => ipAddressV6.GetNetworkAddress(IPAddress.Broadcast);
            fx.Should().Throw<ArgumentException>();
        }

        [Fact]
        public void NetworkingService_GetBroadcastAddress_InvalidSubnet()
        {
            IPAddress ipAddressV6 = IPAddress.IPv6None;

            Func<IPAddress> fx = () => ipAddressV6.GetBroadcastAddress(IPAddress.Broadcast);
            fx.Should().Throw<ArgumentException>();
        }
    }
}