// ***********************************************************************
// Assembly         : PureActive.Network.Services.UnitTests
// Author           : SteveBu
// Created          : 11-17-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="NetworkDeviceBaseUnitTests.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using FluentAssertions;
using PureActive.Network.Abstractions.CommonNetworkServices;
using PureActive.Network.Abstractions.NetworkDevice;
using PureActive.Network.Abstractions.Types;
using PureActive.Network.Devices.Network;
using PureActive.Serilog.Sink.Xunit.TestBase;
using Xunit;
using Xunit.Abstractions;

namespace PureActive.Network.Services.UnitTests.Network
{
    /// <summary>
    /// Class NetworkDeviceBaseUnitTests.
    /// Implements the <see cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{NetworkDeviceBaseUnitTests}" />
    /// </summary>
    /// <seealso cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{NetworkDeviceBaseUnitTests}" />
    /// <autogeneratedoc />
    [Trait("Category", "Unit")]
    public class NetworkDeviceBaseUnitTests : TestBaseLoggable<NetworkDeviceBaseUnitTests>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkDeviceBaseUnitTests"/> class.
        /// </summary>
        /// <param name="testOutputHelper">The test output helper.</param>
        /// <autogeneratedoc />
        public NetworkDeviceBaseUnitTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {
            _commonNetworkServices =
                CommonNetworkServices.CreateInstance(TestLoggerFactory, "NetworkDeviceBaseUnitTests");
        }

        /// <summary>
        /// The common network services
        /// </summary>
        /// <autogeneratedoc />
        private readonly ICommonNetworkServices _commonNetworkServices;

        /// <summary>
        /// Defines the test method NetworkDeviceBase_Constructor.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void NetworkDeviceBase_Constructor()
        {
            NetworkDeviceBase networkDeviceBase =
                new NetworkDeviceBase(_commonNetworkServices, DeviceType.LocalComputer);
            networkDeviceBase.Should().NotBeNull().And.Subject.Should().BeAssignableTo<INetworkDevice>();
        }
    }
}