// ***********************************************************************
// Assembly         : PureActive.Email.Office365
// Author           : SteveBu
// Created          : 11-01-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-01-2018
// ***********************************************************************
// <copyright file="Office365EmailProvider.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using PureActive.Email.Office365.Interfaces;

namespace PureActive.Email.Office365.Providers
{
    /// <summary>
    /// Sends mail messages.
    /// Implements the <see cref="IEmailProvider" />
    /// </summary>
    /// <seealso cref="IEmailProvider" />
    public class Office365EmailProvider : IEmailProvider
    {
        /// <summary>
        /// From
        /// </summary>
        /// <autogeneratedoc />
        private readonly MailAddress _from;

        /// <summary>
        /// The password for all messages
        /// </summary>
        private readonly string _password;

        /// <summary>
        /// The username for all messages
        /// </summary>
        private readonly string _userName;


        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="from">From.</param>
        /// <param name="userName">Name of the user.</param>
        /// <param name="password">The password.</param>
        public Office365EmailProvider(MailAddress from, string userName, string password)
        {
            _userName = userName;
            _password = password;
            _from = from;
        }

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="fromEmail">From email.</param>
        /// <param name="fromName">From name.</param>
        /// <param name="userName">Name of the user.</param>
        /// <param name="password">The password.</param>
        /// <inheritdoc />
        public Office365EmailProvider(string fromEmail, string fromName, string userName, string password) :
            this(new MailAddress(fromEmail, fromName), userName, password)

        {
        }

        /// <summary>
        /// Send a mail message.
        /// </summary>
        /// <param name="recipient">The recipient.</param>
        /// <param name="subject">The subject.</param>
        /// <param name="body">The body.</param>
        /// <param name="isBodyHtml">if set to <c>true</c> [is body HTML].</param>
        /// <returns>Task.</returns>
        /// <autogeneratedoc />
        public Task SendMessageAsync(MailAddress recipient, string subject, string body,
            bool isBodyHtml)
        {
            return SendMessageAsync(new List<MailAddress> {recipient}, subject, body, isBodyHtml);
        }

        /// <summary>
        /// Send a mail message using strings.
        /// </summary>
        /// <param name="email">The email.</param>
        /// <param name="displayName">The display name.</param>
        /// <param name="subject">The subject.</param>
        /// <param name="body">The body.</param>
        /// <param name="isBodyHtml">if set to <c>true</c> [is body HTML].</param>
        /// <returns>Task.</returns>
        /// <autogeneratedoc />
        public Task SendMessageAsync(string email, string displayName, string subject, string body,
            bool isBodyHtml)
        {
            return SendMessageAsync(new MailAddress(email, displayName), subject, body, isBodyHtml);
        }

        /// <summary>
        /// Send a mail message using strings.
        /// </summary>
        /// <param name="email">The email.</param>
        /// <param name="subject">The subject.</param>
        /// <param name="body">The body.</param>
        /// <param name="isBodyHtml">if set to <c>true</c> [is body HTML].</param>
        /// <returns>Task.</returns>
        /// <autogeneratedoc />
        public Task SendMessageAsync(string email, string subject, string body,
            bool isBodyHtml)
        {
            return SendMessageAsync(new MailAddress(email), subject, body, isBodyHtml);
        }

        /// <summary>send message as an asynchronous operation.</summary>
        /// <param name="smtpClient">The SMTP client.</param>
        /// <param name="recipients">The recipients.</param>
        /// <param name="subject">The subject.</param>
        /// <param name="body">The body.</param>
        /// <param name="isBodyHtml">if set to <c>true</c> [is body HTML].</param>
        /// <returns>Task.</returns>
        /// <autogeneratedoc />
        public Task SendMessageAsync(
            SmtpClient smtpClient,
            IList<MailAddress> recipients,
            string subject,
            string body,
            bool isBodyHtml)

        {
            var tos = recipients.Select(r => new MailAddress(r.Address, r.DisplayName)).ToList();

            var msg = new MailMessage
            {
                From = _from,
                Body = body,
                IsBodyHtml = isBodyHtml,
                BodyEncoding = Encoding.UTF8,
                Subject = subject,
                SubjectEncoding = Encoding.UTF8
            };

            // Add each to user
            foreach (var to in tos)
                if (to != null)
                    msg.To.Add(to);

            return smtpClient.SendMailAsync(msg);
        }

        /// <summary>
        /// Send a mail message.
        /// </summary>
        /// <param name="recipients">The recipients.</param>
        /// <param name="subject">The subject.</param>
        /// <param name="body">The body.</param>
        /// <param name="isBodyHtml">if set to <c>true</c> [is body HTML].</param>
        /// <returns>Task.</returns>
        public Task SendMessageAsync(
            IList<MailAddress> recipients,
            string subject,
            string body,
            bool isBodyHtml)
        {
            var client = new SmtpClient("smtp.office365.com", 587)
            {
                EnableSsl = true,
                Credentials = new NetworkCredential(_userName, _password)
            };
           
            return SendMessageAsync(client, recipients, subject, body, isBodyHtml);
        }

        /// <summary>
        /// Sends the email asynchronous. Implements IEmailSender Interface
        /// </summary>
        /// <param name="email">The email.</param>
        /// <param name="subject">The subject.</param>
        /// <param name="htmlMessage">The HTML message.</param>
        /// <returns>Task.</returns>
        /// <autogeneratedoc />
        public Task SendEmailAsync(string email, string subject, string htmlMessage)
        {
            return SendMessageAsync(email, subject, htmlMessage, true);
        }

        /// <summary>
        /// Creates a new Office365 mail provider.
        /// </summary>
        /// <param name="fromEmail">From email.</param>
        /// <param name="fromName">From name.</param>
        /// <param name="userName">Name of the user.</param>
        /// <param name="password">The password.</param>
        /// <returns>IEmailProvider.</returns>
        public static IEmailProvider CreateOffice365MailProvider(
            string fromEmail, string fromName, string userName, string password)
        {
            // string fromEmail, string fromName, string userName, string password

            return new Office365EmailProvider(fromEmail, fromName, userName, password);
        }

        /// <summary>
        /// Creates a new Office365 mail provider from a configuration
        /// </summary>
        /// <param name="configuration">The configuration.</param>
        /// <returns>IEmailProvider.</returns>
        /// <exception cref="ArgumentNullException">configuration</exception>
        public static IEmailProvider CreateOffice365MailProvider(IConfiguration configuration)
        {
            if (configuration == null) throw new ArgumentNullException(nameof(configuration));

            return CreateOffice365MailProvider(
                configuration["Email:EmailAddress"],
                configuration["Email:EmailDisplayName"],
                configuration["Email:Providers:Office365:UserName"],
                configuration["Email:Providers:Office365:Password"]
            );
        }
    }
}