// ***********************************************************************
// Assembly         : PureActive.Network.Devices
// Author           : SteveBu
// Created          : 11-02-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="PureObjectEdge.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using PureActive.Network.Abstractions.PureObject;

namespace PureActive.Network.Devices.PureObjectGraph
{
    /// <summary>
    /// Class PureObjectEdge.
    /// Implements the <see cref="System.IComparable{PureObjectEdge}" />
    /// </summary>
    /// <typeparam name="T"></typeparam>
    /// <seealso cref="System.IComparable{PureObjectEdge}" />
    /// <autogeneratedoc />
    public class PureObjectEdge<T> : IComparable<PureObjectEdge<T>> where T : class, IPureObject
    {
        /// <summary>
        /// The directed
        /// </summary>
        /// <autogeneratedoc />
        private bool _directed;

        /// <summary>
        /// Creates an instance of the edge.
        /// </summary>
        /// <param name="tail">The tail vertex.</param>
        /// <param name="head">The head vertex.</param>
        /// <param name="directed">Indicates if the edge is directed (true) or undirected (false).</param>
        /// <param name="weight">The weight of the edge. Default is 0 (unweighted).</param>
        private PureObjectEdge(PureObjectVertex<T> tail, PureObjectVertex<T> head, bool directed = false,
            double weight = 0)
        {
            EndPoints = new Tuple<PureObjectVertex<T>, PureObjectVertex<T>>(tail, head);
            _directed = directed;
            Weight = weight;
            SetId();
        }

        /// <summary>
        /// Gets the edge's ID.
        /// </summary>
        /// <value>The identifier.</value>
        /// <remarks>The ID is a tuple of Tail.ID, directed indicator (0 means undirected and 1 means directed), and Head.ID.</remarks>
        public (Guid tail, int directed, Guid head) Id { get; internal set; }

        /// <summary>
        /// Gets the endpoints of the edge.
        /// </summary>
        /// <value>The end points.</value>
        public Tuple<PureObjectVertex<T>, PureObjectVertex<T>> EndPoints { get; }

        /// <summary>
        /// Gets the tail of the edge.
        /// </summary>
        /// <value>The tail.</value>
        public PureObjectVertex<T> Tail
        {
            get => EndPoints.Item1;
        }

        /// <summary>
        /// Gets the head of the edge.
        /// </summary>
        /// <value>The head.</value>
        public PureObjectVertex<T> Head
        {
            get => EndPoints.Item2;
        }

        /// <summary>
        /// Gets or sets the weight of the edge.
        /// </summary>
        /// <value>The weight.</value>
        public double Weight { get; set; }

        /// <summary>
        /// Gets or sets if the edge is directed (true) or undirected (false).
        /// </summary>
        /// <value><c>true</c> if directed; otherwise, <c>false</c>.</value>
        public bool Directed
        {
            get => _directed;
            set
            {
                if (_directed != value)
                {
                    _directed = value;
                    SetId();
                }
            }
        }

        /// <summary>
        /// Compares to.
        /// </summary>
        /// <param name="other">The other.</param>
        /// <returns>System.Int32.</returns>
        /// <autogeneratedoc />
        public int CompareTo(PureObjectEdge<T> other)
        {
            return Id.CompareTo(other.Id);
        }

        /// <summary>
        /// Creates an edge.
        /// </summary>
        /// <param name="tail">The tail vertex.</param>
        /// <param name="head">The head vertex.</param>
        /// <param name="directed">Indicates if the edge is directed or not.</param>
        /// <param name="weight">The weight of the edge. Default is 0 (unweighted).</param>
        /// <returns>The edge created.</returns>
        internal static PureObjectEdge<T> Create(PureObjectVertex<T> tail, PureObjectVertex<T> head,
            bool directed = false, double weight = 0) => new PureObjectEdge<T>(tail, head, directed, weight);

        /// <summary>
        /// Deconstructs an edge to its ID parts.
        /// </summary>
        /// <param name="tail">The tail ID.</param>
        /// <param name="directed">An indicator if directed (1) or undirected (0).</param>
        /// <param name="head">The head ID.</param>
        public void Deconstruct(out Guid tail, out int directed, out Guid head)
        {
            tail = EndPoints.Item1.Id;
            directed = ToDirectedIndicator(_directed);
            head = EndPoints.Item2.Id;
        }

        /// <summary>
        /// Sets the edge's ID.
        /// </summary>
        private void SetId()
        {
            (Guid tail, int directed, Guid head) = this;
            Id = (tail, directed, head);
        }

        /// <summary>
        /// Translates a directed flag to its indicator equivalent.
        /// </summary>
        /// <param name="directed">The directed flag.</param>
        /// <returns>The directed flag's indicator equivalent.</returns>
        public static int ToDirectedIndicator(bool directed) => directed ? 1 : 0;
    }
}