// ***********************************************************************
// Assembly         : PureActive.Email.IntegrationTests
// Author           : SteveBu
// Created          : 11-17-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="EmailIntegrationTests.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Net.Mail;
using System.Threading.Tasks;
using FluentAssertions;
using PureActive.Email.Office365.Providers;
using PureActive.Serilog.Sink.Xunit.TestBase;
using Xunit;
using Xunit.Abstractions;

namespace PureActive.Email.IntegrationTests
{
    /// <summary>
    /// Class EmailIntegrationTests.
    /// Implements the <see cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{EmailIntegrationTests}" />
    /// </summary>
    /// <seealso cref="Serilog.Sink.Xunit.TestBase.TestBaseLoggable{EmailIntegrationTests}" />
    /// <autogeneratedoc />
    [Trait("Category", "Integration")]
    public class EmailIntegrationTests : TestBaseLoggable<EmailIntegrationTests>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailIntegrationTests"/> class.
        /// </summary>
        /// <param name="testOutputHelper">The test output helper.</param>
        /// <autogeneratedoc />
        public EmailIntegrationTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {
        }

        /// <summary>
        /// Defines the test method EmailIntegration_Create_Provider.
        /// </summary>
        /// <returns>Task.</returns>
        /// <autogeneratedoc />
        [Fact]
        public void EmailIntegration_Create_Provider()
        {

            var office365EmailProvider = new Office365EmailProvider("stevebu@bushchang.com", "Steve Bush", "stevebu@bushchang.com", "*");

            Func<Task> fx = async () => await office365EmailProvider.SendEmailAsync("stevebu@stevebu.com", "Testing Email", "<HTML><BODY>Testing</BODY></HTML>");

            fx.Should().Throw<SmtpException>();
        }
    }
}