// ***********************************************************************
// Assembly         : PureActive.Logging.Abstractions
// Author           : SteveBu
// Created          : 10-30-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="IPureLoggerGlobal.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace PureActive.Logging.Abstractions.Interfaces
{
    /// <summary>
    /// Interface IPureLoggerGlobal
    /// </summary>
    /// <autogeneratedoc />
    public interface IPureLoggerGlobal
    {
        /// <summary>
        /// Gets or sets the application logger.
        /// </summary>
        /// <value>The application logger.</value>
        /// <autogeneratedoc />
        IPureLogger AppLogger { get; set; }
        /// <summary>
        /// Gets or sets the test logger.
        /// </summary>
        /// <value>The test logger.</value>
        /// <autogeneratedoc />
        IPureLogger TestLogger { get; set; }
    }
}