// ***********************************************************************
// Assembly         : PureActive.Logging.Abstractions
// Author           : SteveBu
// Created          : 11-05-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="IPureLogPropertyLevel.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using Microsoft.Extensions.Logging;

namespace PureActive.Logging.Abstractions.Interfaces
{
    /// <summary>
    /// Interface IPureLogPropertyLevel
    /// Implements the <see cref="PureActive.Logging.Abstractions.Interfaces.IPureLogProperty" />
    /// </summary>
    /// <seealso cref="PureActive.Logging.Abstractions.Interfaces.IPureLogProperty" />
    /// <autogeneratedoc />
    public interface IPureLogPropertyLevel : IPureLogProperty
    {
        /// <summary>
        /// Gets the minimum log level.
        /// </summary>
        /// <value>The minimum log level.</value>
        /// <autogeneratedoc />
        LogLevel MinimumLogLevel { get; }
    }
}