// ***********************************************************************
// Assembly         : PureActive.Logger.Provider.Serilog.UnitTests
// Author           : SteveBu
// Created          : 11-25-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-25-2018
// ***********************************************************************
// <copyright file="PureSeriLoggerFactoryUnitTests.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************

using System;
using FluentAssertions;
using Microsoft.Extensions.Logging;
using PureActive.Core.System;
using PureActive.Logger.Provider.Serilog.Configuration;
using PureActive.Logger.Provider.Serilog.Interfaces;
using PureActive.Logger.Provider.Serilog.Settings;
using PureActive.Logger.Provider.Serilog.Types;
using PureActive.Logging.Abstractions.Interfaces;
using PureActive.Logging.Abstractions.Types;
using PureActive.Serilog.Sink.Xunit.TestBase;
using Serilog;
using Serilog.Events;
using Xunit;
using Xunit.Abstractions;
using ILogger = Microsoft.Extensions.Logging.ILogger;

namespace PureActive.Logger.Provider.Serilog.UnitTests.Types
{

    /// <summary>
    /// Class PureSeriLoggerFactoryUnitTests.
    /// Implements the <see cref="PureSeriLoggerFactoryUnitTests" />
    /// </summary>
    /// <seealso cref="PureSeriLoggerFactoryUnitTests" />
    /// <autogeneratedoc />
    [Trait("Category", "Unit")]
    public class PureSeriLoggerFactoryUnitTests : TestBaseLoggable<PureSeriLoggerFactoryUnitTests>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PureSeriLoggerFactoryUnitTests"/> class.
        /// </summary>
        /// <param name="testOutputHelper">The test output helper.</param>
        /// <autogeneratedoc />
        public PureSeriLoggerFactoryUnitTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {
            _pureSeriLoggerFactory = new PureSeriLoggerFactory(TestLoggerFactory, LoggerSettings);
        }

        /// <summary>
        /// The pure seri logger factory
        /// </summary>
        /// <autogeneratedoc />
        private readonly IPureLoggerFactory _pureSeriLoggerFactory;

        /// <summary>
        /// Defines the test method PureSeriLoggerFactory_Constructor.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void PureSeriLoggerFactory_Constructor()
        {
           _pureSeriLoggerFactory.Should().NotBeNull().And.Subject.Should().BeAssignableTo<IPureLoggerFactory>();
        }


        /// <summary>
        /// Defines the test method PureSeriLoggerFactory_CreateLogger.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void PureSeriLoggerFactory_CreateLogger()
        {
            var logger = _pureSeriLoggerFactory.CreateLogger(nameof(PureSeriLoggerFactoryUnitTests));
            logger.Should().NotBeNull().And.Subject.Should().BeAssignableTo<ILogger>();
        }

        /// <summary>
        /// Defines the test method PureSeriLoggerFactory_CreateLogger_Type.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void PureSeriLoggerFactory_CreateLogger_Type()
        {
            var logger = _pureSeriLoggerFactory.CreateLogger<PureSeriLoggerFactoryUnitTests>();
            logger.Should().NotBeNull().And.Subject.Should().BeAssignableTo<ILogger<PureSeriLoggerFactoryUnitTests>>();
        }


        /// <summary>
        /// Defines the test method PureSeriLoggerFactory_AddProvider_Null.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void PureSeriLoggerFactory_AddProvider_Null()
        {
           _pureSeriLoggerFactory.AddProvider(null);
        }

        [Fact]
        public void PureSeriLoggerFactory_CreateSerilogFactory_Null()
        {
            Func<ILoggerFactory> fx = () => LoggerConfigurationFactory.CreateSerilogFactory((ISerilogLoggerSettings)null);
            fx.Should().Throw<ArgumentException>().And.ParamName.Should().Be("loggerSettings");
        }

        [Fact]
        public void PureSeriLoggerFactory_CreateSerilogFactory_LoggerConfiguration()
        {
            var loggerSettings = new SerilogLoggerSettings(new FileSystem(typeof(PureSeriLoggerFactoryUnitTests)), LogEventLevel.Debug, LoggingOutputFlags.Default);

            var loggerFactory = LoggerConfigurationFactory.CreateSerilogFactory(loggerSettings);
            loggerFactory.Should().NotBeNull();

        }
    }
}