// ***********************************************************************
// Assembly         : PureActive.Logger.Provider.ApplicationInsights.IntegrationTests
// Author           : SteveBu
// Created          : 11-17-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="ApplicationInsightsProviderIntegrationTests.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************

using PureActive.Serilog.Sink.Xunit.TestBase;
using Xunit;
using Xunit.Abstractions;

namespace PureActive.Logger.Provider.ApplicationInsights.IntegrationTests
{
    /// <summary>
    /// Class ApplicationInsightsProviderIntegrationTests.
    /// Implements the <see cref="PureActive.Serilog.Sink.Xunit.TestBase.TestBaseLoggable{ApplicationInsightsProviderIntegrationTests}" />
    /// </summary>
    /// <seealso cref="PureActive.Serilog.Sink.Xunit.TestBase.TestBaseLoggable{ApplicationInsightsProviderIntegrationTests}" />
    /// <autogeneratedoc />
    [Trait("Category", "Integration")]
    public class ApplicationInsightsProviderIntegrationTests : TestBaseLoggable<ApplicationInsightsProviderIntegrationTests>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplicationInsightsProviderIntegrationTests"/> class.
        /// </summary>
        /// <param name="testOutputHelper">The test output helper.</param>
        /// <autogeneratedoc />
        public ApplicationInsightsProviderIntegrationTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {
        }

        /// <summary>
        /// Defines the test method ApplicationInsightsProvider_Constructor.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void ApplicationInsightsProvider_Constructor()
        {
        }
    }
}