// ***********************************************************************
// Assembly         : PureActive.Samples.ConsoleApp
// Author           : SteveBu
// Created          : 10-20-2018
// License          : Licensed under MIT License, see https://github.com/PureActive/PureActive/blob/master/LICENSE
//
// Last Modified By : SteveBu
// Last Modified On : 11-20-2018
// ***********************************************************************
// <copyright file="Program.cs" company="BushChang Corporation">
//     © 2018 BushChang Corporation. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Diagnostics.CodeAnalysis;

namespace PureActive.Samples.ConsoleApp
{
    /// <summary>
    /// Class Program.
    /// </summary>
    /// <autogeneratedoc />
    [ExcludeFromCodeCoverage]
    public static class Program
    {
        // ReSharper disable once UnusedParameter.Local
        /// <summary>
        /// Defines the entry point of the application.
        /// </summary>
        /// <param name="args">The arguments.</param>
        /// <autogeneratedoc />
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}